-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.9.0.201.0
-- Module  Version: 5.8
--c:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba -w -n sdr -lang vhdl -synth lse -bus_exp 7 -bb -arch sn5w00 -type iol -mode Receive -io_type LVCMOS25 -width 8 -freq_in 100 -aligned -del -1 -gear 1 

-- Wed Dec 07 16:53:23 2016

library IEEE;
use IEEE.std_logic_1164.all;
library lifmd;
use lifmd.components.all;

entity sdr is
    port (
        clkin: in  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        datain: in  std_logic_vector(7 downto 0); 
        q: out  std_logic_vector(7 downto 0));
end sdr;

architecture Structure of sdr is

    -- internal signal declarations
    signal buf_clkin: std_logic;
    signal scuba_vhi: std_logic;
    signal dataini_t7: std_logic;
    signal dataini_t6: std_logic;
    signal dataini_t5: std_logic;
    signal dataini_t4: std_logic;
    signal dataini_t3: std_logic;
    signal dataini_t2: std_logic;
    signal dataini_t1: std_logic;
    signal dataini_t0: std_logic;
    signal buf_dataini7: std_logic;
    signal buf_dataini6: std_logic;
    signal buf_dataini5: std_logic;
    signal buf_dataini4: std_logic;
    signal buf_dataini3: std_logic;
    signal buf_dataini2: std_logic;
    signal buf_dataini1: std_logic;
    signal buf_dataini0: std_logic;

    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst3_IB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB7 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB6 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB5 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB4 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB3 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB2 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB1 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst3_IB: IB
        port map (I=>clkin, O=>buf_clkin);

    Inst2_IFS1P3DX7: IFS1P3DX
        port map (D=>dataini_t7, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(7));

    Inst2_IFS1P3DX6: IFS1P3DX
        port map (D=>dataini_t6, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(6));

    Inst2_IFS1P3DX5: IFS1P3DX
        port map (D=>dataini_t5, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(5));

    Inst2_IFS1P3DX4: IFS1P3DX
        port map (D=>dataini_t4, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(4));

    Inst2_IFS1P3DX3: IFS1P3DX
        port map (D=>dataini_t3, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(3));

    Inst2_IFS1P3DX2: IFS1P3DX
        port map (D=>dataini_t2, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(2));

    Inst2_IFS1P3DX1: IFS1P3DX
        port map (D=>dataini_t1, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(1));

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst2_IFS1P3DX0: IFS1P3DX
        port map (D=>dataini_t0, SP=>scuba_vhi, SCLK=>buf_clkin, 
            CD=>reset, Q=>q(0));

    Inst1_IB7: IB
        port map (I=>datain(7), O=>buf_dataini7);

    Inst1_IB6: IB
        port map (I=>datain(6), O=>buf_dataini6);

    Inst1_IB5: IB
        port map (I=>datain(5), O=>buf_dataini5);

    Inst1_IB4: IB
        port map (I=>datain(4), O=>buf_dataini4);

    Inst1_IB3: IB
        port map (I=>datain(3), O=>buf_dataini3);

    Inst1_IB2: IB
        port map (I=>datain(2), O=>buf_dataini2);

    Inst1_IB1: IB
        port map (I=>datain(1), O=>buf_dataini1);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= buf_clkin;
    dataini_t7 <= buf_dataini7;
    dataini_t6 <= buf_dataini6;
    dataini_t5 <= buf_dataini5;
    dataini_t4 <= buf_dataini4;
    dataini_t3 <= buf_dataini3;
    dataini_t2 <= buf_dataini2;
    dataini_t1 <= buf_dataini1;
    dataini_t0 <= buf_dataini0;
end Structure;
