-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.201.0
-- Module  Version: 5.8
-- Wed Dec 07 16:53:23 2016

-- parameterized module component declaration
component sdr
    port (clkin: in  std_logic; reset: in  std_logic; 
        sclk: out  std_logic; datain: in  std_logic_vector(7 downto 0); 
        q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : sdr
    port map (clkin=>__, reset=>__, sclk=>__, datain(7 downto 0)=>__, q(7 downto 0)=>__);
