/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.5.0.98 */
/* Module Version: 5.2 */
/* Wed Jun 24 17:25:02 2015 */

/* parameterized module instance */
module_top __ (.Din( ), .Addr( ), .Clock( ), .ClockEn( ), .Reset( ), 
    .Q( ));
