/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.5.0.98 */
/* Module Version: 2.8 */
/* Thu May 28 17:04:31 2015 */

/* parameterized module instance */
romblk_64x9_1111_vlog __ (.Address( ), .OutClock( ), .OutClockEn( ), 
    .Reset( ), .Q( ));
