/* Verilog module instantiation template generated by SCUBA Diamond Version 3.3.0.94 */
/* Module Version: 5.6 */
/* Mon Aug 18 17:10:12 2014 */

/* parameterized module instance */
equation_check __ (.CLKI( ), .CLKOP( ));
