/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.78 */
/* Module Version: 5.7 */
/* Thu Jan 15 16:05:13 2015 */

/* parameterized module instance */
module_top __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
