/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.t.332.0
    Soft IP Version: 1.0.1
    Fri Oct 04 12:03:47 2019
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_24M (ref_clk_i, rst_n_i, lock_o, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
endmodule