/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.0.201.0 */
/* Module Version: 4.2 */
/* scuba -w -n maddsub_10x17_dynamic_vlog -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type dspmadd -widtha 10 -widthb 17 -widthsum 28 -gsr ENABLED -area -maddsub -signeda -signedb -rega0 -rega0clk CLK0 -rega0ce CE0 -rega0rst RST0 -rega1 -rega1clk CLK0 -rega1ce CE0 -rega1rst RST0 -regb0 -regb0clk CLK0 -regb0ce CE0 -regb0rst RST0 -regb1 -regb1clk CLK0 -regb1ce CE0 -regb1rst RST0 -regsa0 -regsa0clk CLK0 -regsa0ce CE0 -regsa0rst RST0 -regsb0 -regsb0clk CLK0 -regsb0ce CE0 -regsb0rst RST0 -regsa1 -regsa1clk CLK0 -regsa1ce CE0 -regsa1rst RST0 -regsb1 -regsb1clk CLK0 -regsb1ce CE0 -regsb1rst RST0 -regas0 -regas0clk CLK0 -regas0ce CE0 -regas0rst RST0 -regas1 -regas1clk CLK0 -regas1ce CE0 -regas1rst RST0 -regp0 -regp0clk CLK0 -regp0ce CE0 -regp0rst RST0 -regp1 -regp1clk CLK0 -regp1ce CE0 -regp1rst RST0 -rego -regoclk CLK0 -regoce CE0 -regorst RST0 -clk0 -ce0 -rst0 -e  */
/* Wed Dec 07 16:14:31 2016 */


`timescale 1 ns / 1 ps
module maddsub_10x17_dynamic_vlog (CLK0, CE0, RST0, SignA, SignB, 
    ADDNSUB, A0, A1, B0, B1, SUM)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLK0;
    input wire CE0;
    input wire RST0;
    input wire SignA;
    input wire SignB;
    input wire ADDNSUB;
    input wire [9:0] A0;
    input wire [9:0] A1;
    input wire [16:0] B0;
    input wire [16:0] B1;
    output wire [27:0] SUM;

    wire maddsub_10x17_dynamic_vlog_alu_signedr_1_0;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_53;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_52;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_51;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_50;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_49;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_48;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_47;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_46;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_45;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_44;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_43;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_42;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_41;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_40;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_39;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_38;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_37;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_36;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_35;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_34;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_33;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_32;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_31;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_30;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_29;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_28;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_27;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_26;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_25;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_24;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_23;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_22;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_21;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_20;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_19;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_18;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_17;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_16;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_15;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_14;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_13;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_12;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_11;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_10;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_9;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_8;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_7;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_6;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_5;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_4;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_3;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_2;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_1;
    wire maddsub_10x17_dynamic_vlog_alu_output_r_1_0_0;
    wire maddsub_10x17_dynamic_vlog_alu_signedcin_1_0;
    wire addsub_inv;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_53;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_52;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_51;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_50;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_49;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_48;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_47;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_46;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_45;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_44;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_43;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_42;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_41;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_40;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_39;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_38;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_37;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_36;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_35;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_34;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_33;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_32;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_31;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_30;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_29;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_28;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_27;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_26;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_25;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_24;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_23;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_22;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_21;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_20;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_19;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_18;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_17;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_16;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_15;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_14;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_13;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_12;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_11;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_10;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_9;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_8;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_7;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_6;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_5;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_4;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_3;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_2;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_1;
    wire maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_35;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_34;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_33;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_32;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_31;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_30;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_29;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_28;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_27;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_26;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_25;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_24;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_23;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_22;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_21;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_20;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_19;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_18;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_0_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_signedp_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_35;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_34;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_33;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_32;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_31;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_30;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_29;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_28;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_27;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_26;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_25;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_24;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_23;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_22;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_21;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_20;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_19;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_18;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_17;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_16;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_15;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_14;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_13;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_12;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_11;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_10;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_9;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_8;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_7;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_6;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_5;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_4;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_3;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_2;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_1;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_p_1_0;
    wire maddsub_10x17_dynamic_vlog_0_mult_out_signedp_1;
    wire scuba_vhi;
    wire scuba_vlo;

    INV INV_0 (.A(ADDNSUB), .Z(addsub_inv));

    defparam dsp_alu_0.REG_OPCODEIN_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_INPUTC1_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC1_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_INPUTC0_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC0_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC0_CLK = "NONE" ;
    defparam dsp_alu_0.LEGACY = "ENABLED" ;
    defparam dsp_alu_0.REG_FLAG_RST = "RST0" ;
    defparam dsp_alu_0.REG_FLAG_CE = "CE0" ;
    defparam dsp_alu_0.REG_FLAG_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OUTPUT1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_OUTPUT0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CLK = "CLK0" ;
    defparam dsp_alu_0.MULT9_MODE = "DISABLED" ;
    defparam dsp_alu_0.RNDPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MCPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASK01 = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.MCPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.RESETMODE = "ASYNC" ;
    defparam dsp_alu_0.GSR = "ENABLED" ;
    ALU54A dsp_alu_0 (.CE0(CE0), .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), 
        .CLK0(CLK0), .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo), 
        .RST0(RST0), .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), 
        .SIGNEDIA(maddsub_10x17_dynamic_vlog_0_mult_out_signedp_0), .SIGNEDIB(maddsub_10x17_dynamic_vlog_0_mult_out_signedp_1), 
        .A35(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_17), .A34(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_16), 
        .A33(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_15), .A32(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_14), 
        .A31(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_13), .A30(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_12), 
        .A29(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_11), .A28(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_10), 
        .A27(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_9), .A26(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_8), 
        .A25(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_7), .A24(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_6), 
        .A23(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_5), .A22(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_4), 
        .A21(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_3), .A20(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_2), 
        .A19(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_1), .A18(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_0), 
        .A17(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_17), .A16(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_16), 
        .A15(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_15), .A14(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_14), 
        .A13(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_13), .A12(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_12), 
        .A11(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_11), .A10(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_10), 
        .A9(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_9), .A8(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_8), 
        .A7(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_7), .A6(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_6), 
        .A5(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_5), .A4(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_4), 
        .A3(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_3), .A2(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_2), 
        .A1(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_1), .A0(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_0), 
        .B35(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_17), .B34(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_16), 
        .B33(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_15), .B32(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_14), 
        .B31(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_13), .B30(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_12), 
        .B29(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_11), .B28(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_10), 
        .B27(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_9), .B26(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_8), 
        .B25(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_7), .B24(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_6), 
        .B23(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_5), .B22(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_4), 
        .B21(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_3), .B20(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_2), 
        .B19(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_1), .B18(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_0), 
        .B17(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_17), .B16(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_16), 
        .B15(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_15), .B14(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_14), 
        .B13(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_13), .B12(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_12), 
        .B11(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_11), .B10(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_10), 
        .B9(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_9), .B8(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_8), 
        .B7(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_7), .B6(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_6), 
        .B5(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_5), .B4(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_4), 
        .B3(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_3), .B2(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_2), 
        .B1(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_1), .B0(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_0), 
        .C53(scuba_vlo), .C52(scuba_vlo), .C51(scuba_vlo), .C50(scuba_vlo), 
        .C49(scuba_vlo), .C48(scuba_vlo), .C47(scuba_vlo), .C46(scuba_vlo), 
        .C45(scuba_vlo), .C44(scuba_vlo), .C43(scuba_vlo), .C42(scuba_vlo), 
        .C41(scuba_vlo), .C40(scuba_vlo), .C39(scuba_vlo), .C38(scuba_vlo), 
        .C37(scuba_vlo), .C36(scuba_vlo), .C35(scuba_vlo), .C34(scuba_vlo), 
        .C33(scuba_vlo), .C32(scuba_vlo), .C31(scuba_vlo), .C30(scuba_vlo), 
        .C29(scuba_vlo), .C28(scuba_vlo), .C27(scuba_vlo), .C26(scuba_vlo), 
        .C25(scuba_vlo), .C24(scuba_vlo), .C23(scuba_vlo), .C22(scuba_vlo), 
        .C21(scuba_vlo), .C20(scuba_vlo), .C19(scuba_vlo), .C18(scuba_vlo), 
        .C17(scuba_vlo), .C16(scuba_vlo), .C15(scuba_vlo), .C14(scuba_vlo), 
        .C13(scuba_vlo), .C12(scuba_vlo), .C11(scuba_vlo), .C10(scuba_vlo), 
        .C9(scuba_vlo), .C8(scuba_vlo), .C7(scuba_vlo), .C6(scuba_vlo), 
        .C5(scuba_vlo), .C4(scuba_vlo), .C3(scuba_vlo), .C2(scuba_vlo), 
        .C1(scuba_vlo), .C0(scuba_vlo), .MA35(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_35), 
        .MA34(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_34), .MA33(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_33), 
        .MA32(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_32), .MA31(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_31), 
        .MA30(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_30), .MA29(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_29), 
        .MA28(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_28), .MA27(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_27), 
        .MA26(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_26), .MA25(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_25), 
        .MA24(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_24), .MA23(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_23), 
        .MA22(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_22), .MA21(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_21), 
        .MA20(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_20), .MA19(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_19), 
        .MA18(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_18), .MA17(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_17), 
        .MA16(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_16), .MA15(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_15), 
        .MA14(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_14), .MA13(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_13), 
        .MA12(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_12), .MA11(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_11), 
        .MA10(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_10), .MA9(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_9), 
        .MA8(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_8), .MA7(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_7), 
        .MA6(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_6), .MA5(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_5), 
        .MA4(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_4), .MA3(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_3), 
        .MA2(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_2), .MA1(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_1), 
        .MA0(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_0), .MB35(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_35), 
        .MB34(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_34), .MB33(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_33), 
        .MB32(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_32), .MB31(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_31), 
        .MB30(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_30), .MB29(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_29), 
        .MB28(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_28), .MB27(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_27), 
        .MB26(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_26), .MB25(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_25), 
        .MB24(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_24), .MB23(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_23), 
        .MB22(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_22), .MB21(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_21), 
        .MB20(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_20), .MB19(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_19), 
        .MB18(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_18), .MB17(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_17), 
        .MB16(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_16), .MB15(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_15), 
        .MB14(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_14), .MB13(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_13), 
        .MB12(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_12), .MB11(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_11), 
        .MB10(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_10), .MB9(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_9), 
        .MB8(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_8), .MB7(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_7), 
        .MB6(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_6), .MB5(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_5), 
        .MB4(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_4), .MB3(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_3), 
        .MB2(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_2), .MB1(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_1), 
        .MB0(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_0), .CIN53(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_53), 
        .CIN52(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_52), .CIN51(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_51), 
        .CIN50(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_50), .CIN49(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_49), 
        .CIN48(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_48), .CIN47(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_47), 
        .CIN46(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_46), .CIN45(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_45), 
        .CIN44(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_44), .CIN43(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_43), 
        .CIN42(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_42), .CIN41(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_41), 
        .CIN40(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_40), .CIN39(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_39), 
        .CIN38(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_38), .CIN37(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_37), 
        .CIN36(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_36), .CIN35(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_35), 
        .CIN34(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_34), .CIN33(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_33), 
        .CIN32(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_32), .CIN31(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_31), 
        .CIN30(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_30), .CIN29(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_29), 
        .CIN28(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_28), .CIN27(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_27), 
        .CIN26(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_26), .CIN25(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_25), 
        .CIN24(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_24), .CIN23(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_23), 
        .CIN22(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_22), .CIN21(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_21), 
        .CIN20(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_20), .CIN19(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_19), 
        .CIN18(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_18), .CIN17(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_17), 
        .CIN16(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_16), .CIN15(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_15), 
        .CIN14(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_14), .CIN13(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_13), 
        .CIN12(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_12), .CIN11(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_11), 
        .CIN10(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_10), .CIN9(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_9), 
        .CIN8(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_8), .CIN7(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_7), 
        .CIN6(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_6), .CIN5(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_5), 
        .CIN4(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_4), .CIN3(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_3), 
        .CIN2(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_2), .CIN1(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_1), 
        .CIN0(maddsub_10x17_dynamic_vlog_alu_in_cin_1_0_0), .SIGNEDCIN(maddsub_10x17_dynamic_vlog_alu_signedcin_1_0), 
        .OP10(scuba_vlo), .OP9(scuba_vhi), .OP8(scuba_vlo), .OP7(addsub_inv), 
        .OP6(scuba_vlo), .OP5(scuba_vlo), .OP4(scuba_vlo), .OP3(scuba_vlo), 
        .OP2(scuba_vhi), .OP1(scuba_vlo), .OP0(scuba_vhi), .R53(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_53), 
        .R52(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_52), .R51(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_51), 
        .R50(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_50), .R49(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_49), 
        .R48(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_48), .R47(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_47), 
        .R46(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_46), .R45(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_45), 
        .R44(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_44), .R43(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_43), 
        .R42(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_42), .R41(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_41), 
        .R40(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_40), .R39(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_39), 
        .R38(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_38), .R37(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_37), 
        .R36(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_36), .R35(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_35), 
        .R34(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_34), .R33(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_33), 
        .R32(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_32), .R31(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_31), 
        .R30(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_30), .R29(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_29), 
        .R28(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_28), .R27(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_27), 
        .R26(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_26), .R25(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_25), 
        .R24(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_24), .R23(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_23), 
        .R22(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_22), .R21(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_21), 
        .R20(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_20), .R19(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_19), 
        .R18(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_18), .R17(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_17), 
        .R16(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_16), .R15(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_15), 
        .R14(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_14), .R13(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_13), 
        .R12(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_12), .R11(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_11), 
        .R10(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_10), .R9(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_9), 
        .R8(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_8), .R7(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_7), 
        .R6(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_6), .R5(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_5), 
        .R4(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_4), .R3(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_3), 
        .R2(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_2), .R1(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_1), 
        .R0(maddsub_10x17_dynamic_vlog_alu_output_r_1_0_0), .EQZ(), .EQZM(), 
        .EQOM(), .EQPAT(), .EQPATB(), .OVER(), .UNDER(), .OVERUNDER(), .SIGNEDR(maddsub_10x17_dynamic_vlog_alu_signedr_1_0));

    defparam dsp_mult_1.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_1.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_1.RESETMODE = "ASYNC" ;
    defparam dsp_mult_1.GSR = "ENABLED" ;
    defparam dsp_mult_1.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_1.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_1.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_1.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_1.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_1.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18C dsp_mult_1 (.A17(A0[9]), .A16(A0[8]), .A15(A0[7]), .A14(A0[6]), 
        .A13(A0[5]), .A12(A0[4]), .A11(A0[3]), .A10(A0[2]), .A9(A0[1]), 
        .A8(A0[0]), .A7(scuba_vlo), .A6(scuba_vlo), .A5(scuba_vlo), .A4(scuba_vlo), 
        .A3(scuba_vlo), .A2(scuba_vlo), .A1(scuba_vlo), .A0(scuba_vlo), 
        .B17(B0[16]), .B16(B0[15]), .B15(B0[14]), .B14(B0[13]), .B13(B0[12]), 
        .B12(B0[11]), .B11(B0[10]), .B10(B0[9]), .B9(B0[8]), .B8(B0[7]), 
        .B7(B0[6]), .B6(B0[5]), .B5(B0[4]), .B4(B0[3]), .B3(B0[2]), .B2(B0[1]), 
        .B1(B0[0]), .B0(scuba_vlo), .SIGNEDA(SignA), .SIGNEDB(SignB), .SOURCEA(scuba_vlo), 
        .SOURCEB(scuba_vlo), .CE0(CE0), .CE1(scuba_vhi), .CE2(scuba_vhi), 
        .CE3(scuba_vhi), .CLK0(CLK0), .CLK1(scuba_vlo), .CLK2(scuba_vlo), 
        .CLK3(scuba_vlo), .RST0(RST0), .RST1(scuba_vlo), .RST2(scuba_vlo), 
        .RST3(scuba_vlo), .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), 
        .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), 
        .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), 
        .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), 
        .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), 
        .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), 
        .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), 
        .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), 
        .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), 
        .SRIB0(scuba_vlo), .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), 
        .SROA12(), .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), 
        .SROA5(), .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), 
        .SROB16(), .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), 
        .SROB10(), .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), 
        .SROB3(), .SROB2(), .SROB1(), .SROB0(), .ROA17(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_17), 
        .ROA16(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_16), .ROA15(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_15), 
        .ROA14(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_14), .ROA13(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_13), 
        .ROA12(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_12), .ROA11(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_11), 
        .ROA10(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_10), .ROA9(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_9), 
        .ROA8(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_8), .ROA7(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_7), 
        .ROA6(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_6), .ROA5(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_5), 
        .ROA4(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_4), .ROA3(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_3), 
        .ROA2(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_2), .ROA1(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_1), 
        .ROA0(maddsub_10x17_dynamic_vlog_0_mult_out_roa_0_0), .ROB17(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_17), 
        .ROB16(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_16), .ROB15(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_15), 
        .ROB14(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_14), .ROB13(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_13), 
        .ROB12(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_12), .ROB11(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_11), 
        .ROB10(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_10), .ROB9(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_9), 
        .ROB8(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_8), .ROB7(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_7), 
        .ROB6(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_6), .ROB5(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_5), 
        .ROB4(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_4), .ROB3(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_3), 
        .ROB2(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_2), .ROB1(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_1), 
        .ROB0(maddsub_10x17_dynamic_vlog_0_mult_out_rob_0_0), .P35(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_35), 
        .P34(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_34), .P33(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_33), 
        .P32(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_32), .P31(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_31), 
        .P30(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_30), .P29(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_29), 
        .P28(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_28), .P27(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_27), 
        .P26(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_26), .P25(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_25), 
        .P24(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_24), .P23(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_23), 
        .P22(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_22), .P21(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_21), 
        .P20(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_20), .P19(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_19), 
        .P18(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_18), .P17(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_17), 
        .P16(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_16), .P15(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_15), 
        .P14(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_14), .P13(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_13), 
        .P12(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_12), .P11(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_11), 
        .P10(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_10), .P9(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_9), 
        .P8(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_8), .P7(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_7), 
        .P6(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_6), .P5(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_5), 
        .P4(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_4), .P3(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_3), 
        .P2(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_2), .P1(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_1), 
        .P0(maddsub_10x17_dynamic_vlog_0_mult_out_p_0_0), .SIGNEDP(maddsub_10x17_dynamic_vlog_0_mult_out_signedp_0));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam dsp_mult_0.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_0.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_0.RESETMODE = "ASYNC" ;
    defparam dsp_mult_0.GSR = "ENABLED" ;
    defparam dsp_mult_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_0.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_0.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18C dsp_mult_0 (.A17(A1[9]), .A16(A1[8]), .A15(A1[7]), .A14(A1[6]), 
        .A13(A1[5]), .A12(A1[4]), .A11(A1[3]), .A10(A1[2]), .A9(A1[1]), 
        .A8(A1[0]), .A7(scuba_vlo), .A6(scuba_vlo), .A5(scuba_vlo), .A4(scuba_vlo), 
        .A3(scuba_vlo), .A2(scuba_vlo), .A1(scuba_vlo), .A0(scuba_vlo), 
        .B17(B1[16]), .B16(B1[15]), .B15(B1[14]), .B14(B1[13]), .B13(B1[12]), 
        .B12(B1[11]), .B11(B1[10]), .B10(B1[9]), .B9(B1[8]), .B8(B1[7]), 
        .B7(B1[6]), .B6(B1[5]), .B5(B1[4]), .B4(B1[3]), .B3(B1[2]), .B2(B1[1]), 
        .B1(B1[0]), .B0(scuba_vlo), .SIGNEDA(SignA), .SIGNEDB(SignB), .SOURCEA(scuba_vlo), 
        .SOURCEB(scuba_vlo), .CE0(CE0), .CE1(scuba_vhi), .CE2(scuba_vhi), 
        .CE3(scuba_vhi), .CLK0(CLK0), .CLK1(scuba_vlo), .CLK2(scuba_vlo), 
        .CLK3(scuba_vlo), .RST0(RST0), .RST1(scuba_vlo), .RST2(scuba_vlo), 
        .RST3(scuba_vlo), .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), 
        .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), 
        .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), 
        .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), 
        .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), 
        .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), 
        .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), 
        .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), 
        .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), 
        .SRIB0(scuba_vlo), .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), 
        .SROA12(), .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), 
        .SROA5(), .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), 
        .SROB16(), .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), 
        .SROB10(), .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), 
        .SROB3(), .SROB2(), .SROB1(), .SROB0(), .ROA17(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_17), 
        .ROA16(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_16), .ROA15(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_15), 
        .ROA14(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_14), .ROA13(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_13), 
        .ROA12(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_12), .ROA11(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_11), 
        .ROA10(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_10), .ROA9(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_9), 
        .ROA8(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_8), .ROA7(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_7), 
        .ROA6(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_6), .ROA5(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_5), 
        .ROA4(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_4), .ROA3(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_3), 
        .ROA2(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_2), .ROA1(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_1), 
        .ROA0(maddsub_10x17_dynamic_vlog_0_mult_out_roa_1_0), .ROB17(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_17), 
        .ROB16(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_16), .ROB15(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_15), 
        .ROB14(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_14), .ROB13(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_13), 
        .ROB12(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_12), .ROB11(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_11), 
        .ROB10(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_10), .ROB9(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_9), 
        .ROB8(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_8), .ROB7(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_7), 
        .ROB6(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_6), .ROB5(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_5), 
        .ROB4(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_4), .ROB3(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_3), 
        .ROB2(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_2), .ROB1(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_1), 
        .ROB0(maddsub_10x17_dynamic_vlog_0_mult_out_rob_1_0), .P35(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_35), 
        .P34(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_34), .P33(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_33), 
        .P32(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_32), .P31(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_31), 
        .P30(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_30), .P29(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_29), 
        .P28(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_28), .P27(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_27), 
        .P26(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_26), .P25(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_25), 
        .P24(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_24), .P23(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_23), 
        .P22(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_22), .P21(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_21), 
        .P20(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_20), .P19(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_19), 
        .P18(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_18), .P17(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_17), 
        .P16(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_16), .P15(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_15), 
        .P14(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_14), .P13(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_13), 
        .P12(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_12), .P11(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_11), 
        .P10(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_10), .P9(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_9), 
        .P8(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_8), .P7(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_7), 
        .P6(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_6), .P5(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_5), 
        .P4(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_4), .P3(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_3), 
        .P2(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_2), .P1(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_1), 
        .P0(maddsub_10x17_dynamic_vlog_0_mult_out_p_1_0), .SIGNEDP(maddsub_10x17_dynamic_vlog_0_mult_out_signedp_1));

    assign SUM[27] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_36;
    assign SUM[26] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_35;
    assign SUM[25] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_34;
    assign SUM[24] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_33;
    assign SUM[23] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_32;
    assign SUM[22] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_31;
    assign SUM[21] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_30;
    assign SUM[20] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_29;
    assign SUM[19] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_28;
    assign SUM[18] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_27;
    assign SUM[17] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_26;
    assign SUM[16] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_25;
    assign SUM[15] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_24;
    assign SUM[14] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_23;
    assign SUM[13] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_22;
    assign SUM[12] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_21;
    assign SUM[11] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_20;
    assign SUM[10] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_19;
    assign SUM[9] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_18;
    assign SUM[8] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_17;
    assign SUM[7] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_16;
    assign SUM[6] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_15;
    assign SUM[5] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_14;
    assign SUM[4] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_13;
    assign SUM[3] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_12;
    assign SUM[2] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_11;
    assign SUM[1] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_10;
    assign SUM[0] = maddsub_10x17_dynamic_vlog_alu_output_r_1_0_9;


    // exemplar begin
    // exemplar end

endmodule
