/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.201.0 */
/* Module Version: 4.2 */
/* Wed Dec 07 16:14:31 2016 */

/* parameterized module instance */
maddsub_10x17_dynamic_vlog __ (.CLK0( ), .CE0( ), .RST0( ), .SignA( ), 
    .SignB( ), .ADDNSUB( ), .A0( ), .A1( ), .B0( ), .B1( ), .SUM( ));
