/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.201.0 */
/* Module Version: 5.7 */
/* Wed Dec 07 15:43:14 2016 */

/* parameterized module instance */
equation_check __ (.CLKI( ), .CLKOP( ));
