/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.5.0.91 */
/* Module Version: 3.8 */
/* Tue May 12 10:07:30 2015 */

/* parameterized module instance */
module_top __ (.Address( ), .Data( ), .Clock( ), .WE( ), .ClockEn( ), 
    .Q( ));
