/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.5.0.91 */
/* Module Version: 5.8 */
/* Mon May 11 16:17:54 2015 */

/* parameterized module instance */
sdr __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
