-- VHDL module instantiation generated by SCUBA Diamond_3.0_Production (63)
-- Module  Version: 3.6
-- Thu Jul 04 10:14:12 2013

-- parameterized module component declaration
component ddram_16x11_sap
    port (WrAddress: in  std_logic_vector(3 downto 0); 
        Data: in  std_logic_vector(10 downto 0); WrClock: in  std_logic; 
        WE: in  std_logic; WrClockEn: in  std_logic; 
        RdAddress: in  std_logic_vector(3 downto 0); 
        Q: out  std_logic_vector(10 downto 0));
end component;

-- parameterized module component instance
__ : ddram_16x11_sap
    port map (WrAddress(3 downto 0)=>__, Data(10 downto 0)=>__, WrClock=>__, 
        WE=>__, WrClockEn=>__, RdAddress(3 downto 0)=>__, Q(10 downto 0)=>__);
