-- VHDL module instantiation generated by SCUBA ispLever_v81_SP1_Build (36)
-- Module  Version: 3.5
-- Thu Oct 21 10:40:55 2010

-- parameterized module component declaration
component ddram_16x11_xo2
    port (WrAddress: in  std_logic_vector(3 downto 0); 
        Data: in  std_logic_vector(10 downto 0); WrClock: in  std_logic; 
        WE: in  std_logic; WrClockEn: in  std_logic; 
        RdAddress: in  std_logic_vector(3 downto 0); 
        Q: out  std_logic_vector(10 downto 0));
end component;

-- parameterized module component instance
__ : ddram_16x11_xo2
    port map (WrAddress(3 downto 0)=>__, Data(10 downto 0)=>__, WrClock=>__, 
        WE=>__, WrClockEn=>__, RdAddress(3 downto 0)=>__, Q(10 downto 0)=>__);
