/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.5.0.98 */
/* Module Version: 5.2 */
/* C:\lscc\diamond\3.5_x64\ispfpga\bin\nt64\scuba.exe -w -n module_top -lang verilog -synth lse -bus_exp 7 -bb -arch sn5w00 -type shiftreg -width 12 -depth 16 -mode 10 -pipe_final_output -fdc C:/Users/jwang1/Desktop/temp/MODEL/module_top/module_top.fdc  */
/* Wed Jun 24 17:25:02 2015 */


`timescale 1 ns / 1 ps
module module_top (Din, Addr, Clock, ClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [11:0] Din;
    input wire [3:0] Addr;
    input wire Clock;
    input wire ClockEn;
    input wire Reset;
    output wire [11:0] Q;

    wire Reset_inv;
    wire ishreg_addr_w0;
    wire ishreg_addr_w1;
    wire sreg_0_ctr_1_ci;
    wire ishreg_addr_w2;
    wire ishreg_addr_w3;
    wire co1;
    wire co0;
    wire shreg_addr_r0;
    wire high_inv;
    wire shreg_addr_w0;
    wire precin;
    wire shreg_addr_r1;
    wire shreg_addr_r2;
    wire shreg_addr_w2;
    wire shreg_addr_w1;
    wire co0_1;
    wire shreg_addr_r3;
    wire scuba_vhi;
    wire scuba_vlo;
    wire shreg_addr_w3;
    wire co1_1;

    INV INV_1 (.A(Reset), .Z(Reset_inv));

    INV INV_0 (.A(scuba_vhi), .Z(high_inv));

    defparam sram_1_0_0_0.INIT_DATA = "STATIC" ;
    defparam sram_1_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam sram_1_0_0_0.CSDECODE_R = "0b000" ;
    defparam sram_1_0_0_0.CSDECODE_W = "0b001" ;
    defparam sram_1_0_0_0.GSR = "ENABLED" ;
    defparam sram_1_0_0_0.RESETMODE = "ASYNC" ;
    defparam sram_1_0_0_0.REGMODE = "OUTREG" ;
    defparam sram_1_0_0_0.DATA_WIDTH_R = 18 ;
    defparam sram_1_0_0_0.DATA_WIDTH_W = 18 ;
    PDPW8KE sram_1_0_0_0 (.DI17(scuba_vlo), .DI16(scuba_vlo), .DI15(scuba_vlo), 
        .DI14(scuba_vlo), .DI13(scuba_vlo), .DI12(scuba_vlo), .DI11(Din[11]), 
        .DI10(Din[10]), .DI9(Din[9]), .DI8(Din[8]), .DI7(Din[7]), .DI6(Din[6]), 
        .DI5(Din[5]), .DI4(Din[4]), .DI3(Din[3]), .DI2(Din[2]), .DI1(Din[1]), 
        .DI0(Din[0]), .ADW8(scuba_vlo), .ADW7(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW5(scuba_vlo), .ADW4(scuba_vlo), .ADW3(shreg_addr_w3), .ADW2(shreg_addr_w2), 
        .ADW1(shreg_addr_w1), .ADW0(shreg_addr_w0), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(ClockEn), .CLKW(Clock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(Reset_inv), .ADR12(scuba_vlo), .ADR11(scuba_vlo), .ADR10(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR8(scuba_vlo), .ADR7(shreg_addr_r3), .ADR6(shreg_addr_r2), 
        .ADR5(shreg_addr_r1), .ADR4(shreg_addr_r0), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(ClockEn), .OCER(ClockEn), 
        .CLKR(Clock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[8]), .DO16(Q[7]), .DO15(Q[6]), .DO14(Q[5]), 
        .DO13(Q[4]), .DO12(Q[3]), .DO11(Q[2]), .DO10(Q[1]), .DO9(Q[0]), 
        .DO8(), .DO7(), .DO6(), .DO5(), .DO4(), .DO3(), .DO2(Q[11]), .DO1(Q[10]), 
        .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="module_top.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_3 (.D(ishreg_addr_w0), .SP(ClockEn), .CK(Clock), .CD(Reset), 
        .Q(shreg_addr_w0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(ishreg_addr_w1), .SP(ClockEn), .CK(Clock), .CD(Reset), 
        .Q(shreg_addr_w1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(ishreg_addr_w2), .SP(ClockEn), .CK(Clock), .CD(Reset), 
        .Q(shreg_addr_w2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(ishreg_addr_w3), .SP(ClockEn), .CK(Clock), .CD(Reset), 
        .Q(shreg_addr_w3))
             /* synthesis GSR="ENABLED" */;

    defparam sreg_0_ctr_1_cia.INJECT1_1 = "NO" ;
    defparam sreg_0_ctr_1_cia.INJECT1_0 = "NO" ;
    defparam sreg_0_ctr_1_cia.INIT1 =  16'h66AA ;
    defparam sreg_0_ctr_1_cia.INIT0 =  16'h66AA ;
    CCU2C sreg_0_ctr_1_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(sreg_0_ctr_1_ci));

    defparam sreg_0_ctr_1_0.INJECT1_1 = "NO" ;
    defparam sreg_0_ctr_1_0.INJECT1_0 = "NO" ;
    defparam sreg_0_ctr_1_0.INIT1 =  16'h66AA ;
    defparam sreg_0_ctr_1_0.INIT0 =  16'h66AA ;
    CCU2C sreg_0_ctr_1_0 (.A0(shreg_addr_w0), .A1(shreg_addr_w1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(sreg_0_ctr_1_ci), .S0(ishreg_addr_w0), .S1(ishreg_addr_w1), 
        .COUT(co0));

    defparam sreg_0_ctr_1_1.INJECT1_1 = "NO" ;
    defparam sreg_0_ctr_1_1.INJECT1_0 = "NO" ;
    defparam sreg_0_ctr_1_1.INIT1 =  16'h66AA ;
    defparam sreg_0_ctr_1_1.INIT0 =  16'h66AA ;
    CCU2C sreg_0_ctr_1_1 (.A0(shreg_addr_w2), .A1(shreg_addr_w3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0), .S0(ishreg_addr_w2), .S1(ishreg_addr_w3), 
        .COUT(co1));

    defparam precin_inst50.INJECT1_1 = "NO" ;
    defparam precin_inst50.INJECT1_0 = "NO" ;
    defparam precin_inst50.INIT1 =  16'h0000 ;
    defparam precin_inst50.INIT0 =  16'h0000 ;
    CCU2C precin_inst50 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin));

    defparam raddr_sub_1_0.INJECT1_1 = "NO" ;
    defparam raddr_sub_1_0.INJECT1_0 = "NO" ;
    defparam raddr_sub_1_0.INIT1 =  16'h99AA ;
    defparam raddr_sub_1_0.INIT0 =  16'h99AA ;
    CCU2C raddr_sub_1_0 (.A0(scuba_vhi), .A1(shreg_addr_w0), .B0(high_inv), 
        .B1(Addr[0]), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin), .S0(), .S1(shreg_addr_r0), .COUT(co0_1));

    defparam raddr_sub_1_1.INJECT1_1 = "NO" ;
    defparam raddr_sub_1_1.INJECT1_0 = "NO" ;
    defparam raddr_sub_1_1.INIT1 =  16'h99AA ;
    defparam raddr_sub_1_1.INIT0 =  16'h99AA ;
    CCU2C raddr_sub_1_1 (.A0(shreg_addr_w1), .A1(shreg_addr_w2), .B0(Addr[1]), 
        .B1(Addr[2]), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(shreg_addr_r1), .S1(shreg_addr_r2), .COUT(co1_1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam raddr_sub_1_2.INJECT1_1 = "NO" ;
    defparam raddr_sub_1_2.INJECT1_0 = "NO" ;
    defparam raddr_sub_1_2.INIT1 =  16'h99AA ;
    defparam raddr_sub_1_2.INIT0 =  16'h99AA ;
    CCU2C raddr_sub_1_2 (.A0(shreg_addr_w3), .A1(scuba_vlo), .B0(Addr[3]), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_1), .S0(shreg_addr_r3), .S1(), .COUT());



    // exemplar begin
    // exemplar attribute sram_1_0_0_0 MEM_LPC_FILE module_top.lpc
    // exemplar attribute sram_1_0_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
