//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.5.0.98
`timescale 1 ns / 1 ps
module tb;
    reg [11:0] Din = 12'b0;
    reg [3:0] Addr = 4'b0;
    reg Clock = 0;
    reg ClockEn = 0;
    reg Reset = 0;
    wire [11:0] Q;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    module_top u1 (.Din(Din), .Addr(Addr), .Clock(Clock), .ClockEn(ClockEn), 
        .Reset(Reset), .Q(Q)
    );

    initial
    begin
       Din <= 0;
      #100;
      @(Reset == 1'b0);
      for (i1 = 0; i1 < 19; i1 = i1 + 1) begin
        @(posedge Clock);
        #1  Din <= Din + 1'b1;
      end
    end
    initial
    begin
       Addr <= 0;
      #100;
      @(Reset == 1'b0);
      for (i2 = 0; i2 < 38; i2 = i2 + 1) begin
        @(posedge Clock);
        #1  Addr <= Addr + 1'b1;
      end
    end
    always
    #5.00 Clock <= ~ Clock;

    initial
    begin
       ClockEn <= 1'b0;
      #100;
      @(Reset == 1'b0);
       ClockEn <= 1'b1;
    end
    initial
    begin
       Reset <= 1'b1;
      #100;
       Reset <= 1'b0;
    end
endmodule